[package]
name = "glitcher"
version = "0.1.0"
authors = ["Tiago Carvalho <sugoiuguu@tfwno.gf>"]
edition = "2018"

[dependencies]
actix-web = "3"
actix-multipart = "0.3"
futures-util = "0.3"
serde = { version = "1", name = "serde_derive" }
